name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:
  schedule:
    - cron: 0 0 * * 1

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
